/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#b7c8de',
        'outline': '#74777d',
        'secondary-container': '#d5e0f7',
        'surface-container': '#efedef',
        'tertiary-fixed': '#ffdea6',
        'on-secondary-fixed-variant': '#3c475a',
        'on-surface-variant': '#44474c',
        'surface-container-highest': '#e4e2e3',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'primary-fixed-dim': '#b7c8de',
        'surface-variant': '#e4e2e3',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'surface-dim': '#dbd9db',
        'surface-container-high': '#e9e7e9',
        'primary-container': '#1a2b3c',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#bcc7dd',
        'on-tertiary-fixed-variant': '#5d4200',
        'inverse-on-surface': '#f2f0f2',
        'primary-fixed': '#d2e4fb',
        'surface-bright': '#fbf9fa',
        'inverse-surface': '#303032',
        'tertiary-fixed-dim': '#8a5e0a',
        'on-primary-fixed-variant': '#38485a',
        'outline-variant': '#c4c6cd',
        'tertiary-container': '#382600',
        'background': '#fbf9fa',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#ba880e',
        'on-secondary-fixed': '#111c2c',
        'on-primary-container': '#8192a7',
        'tertiary': '#1e1300',
        'surface-container-low': '#f5f3f4',
        'on-secondary-container': '#586377',
        'surface-tint': '#4f6073',
        'primary': '#041627',
        'on-background': '#1b1c1d',
        'surface': '#fbf9fa',
        'secondary': '#545f72',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#271900',
        'on-primary-fixed': '#0b1d2d',
        'secondary-fixed': '#d8e3fa',
        'on-secondary': '#ffffff',
        'on-surface': '#1b1c1d',
      },
      fontFamily: {
        headline: ['"Barlow Condensed"', 'system-ui', 'sans-serif'],
        body: ['Gelasio', 'Georgia', 'serif'],
        label: ['"Barlow Condensed"', 'system-ui', 'sans-serif'],
        serif: ['"Barlow Condensed"', 'system-ui', 'sans-serif'],
        sans: ['"Barlow Condensed"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
